-- MySQL Script generated by MySQL Workbench
-- mar 24 ene 2023 00:06:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TITULACIÓN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TITULACIÓN` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TITULACIÓN` (
  `idTit` INT NOT NULL,
  `nivel` ENUM("GS", "GM", "GB") NOT NULL,
  `nombreCurso` VARCHAR(45) NULL,
  PRIMARY KEY (`idTit`),
  UNIQUE INDEX `idTit_UNIQUE` (`idTit` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`MATRCICULA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MATRCICULA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MATRCICULA` (
  `codPago` INT NOT NULL,
  `curso` DATE NULL,
  `TITULACIÓN_idTit` INT NOT NULL,
  PRIMARY KEY (`codPago`),
  UNIQUE INDEX `codPago_UNIQUE` (`codPago` ASC) VISIBLE,
  INDEX `fk_MATRCICULA_TITULACIÓN1_idx` (`TITULACIÓN_idTit` ASC) VISIBLE,
  CONSTRAINT `fk_MATRCICULA_TITULACIÓN1`
    FOREIGN KEY (`TITULACIÓN_idTit`)
    REFERENCES `mydb`.`TITULACIÓN` (`idTit`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`ESTUDIANTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ESTUDIANTE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ESTUDIANTE` (
  `numExpediente` INT NOT NULL,
  `titulacion` VARCHAR(45) NOT NULL,
  `MATRCICULA_codPago` INT NOT NULL,
  PRIMARY KEY (`numExpediente`),
  INDEX `fk_ESTUDIANTE_MATRCICULA1_idx` (`MATRCICULA_codPago` ASC) VISIBLE,
  UNIQUE INDEX `MATRCICULA_codPago_UNIQUE` (`MATRCICULA_codPago` ASC) VISIBLE,
  CONSTRAINT `fk_ESTUDIANTE_MATRCICULA1`
    FOREIGN KEY (`MATRCICULA_codPago`)
    REFERENCES `mydb`.`MATRCICULA` (`codPago`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`ESPECIALIDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ESPECIALIDAD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ESPECIALIDAD` (
  `identificador` CHAR(15) NOT NULL,
  `nombreEsp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`identificador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`DOCENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DOCENTE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DOCENTE` (
  `NRP` CHAR(17) NOT NULL,
  `acronimo` CHAR(10) NULL,
  `ESPECIALIDAD_identificador` CHAR(15) NOT NULL,
  PRIMARY KEY (`NRP`),
  INDEX `fk_DOCENTE_ESPECIALIDAD1_idx` (`ESPECIALIDAD_identificador` ASC) VISIBLE,
  CONSTRAINT `fk_DOCENTE_ESPECIALIDAD1`
    FOREIGN KEY (`ESPECIALIDAD_identificador`)
    REFERENCES `mydb`.`ESPECIALIDAD` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `dni` CHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NULL,
  `ESTUDIANTE_numExpediente` INT NOT NULL,
  `DOCENTE_NRP` CHAR(17) NOT NULL,
  PRIMARY KEY (`dni`),
  INDEX `fk_USUARIO_ESTUDIANTE1_idx` (`ESTUDIANTE_numExpediente` ASC) VISIBLE,
  INDEX `fk_USUARIO_DOCENTE1_idx` (`DOCENTE_NRP` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_ESTUDIANTE1`
    FOREIGN KEY (`ESTUDIANTE_numExpediente`)
    REFERENCES `mydb`.`ESTUDIANTE` (`numExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_DOCENTE1`
    FOREIGN KEY (`DOCENTE_NRP`)
    REFERENCES `mydb`.`DOCENTE` (`NRP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`GRUPO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GRUPO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GRUPO` (
  `codGrupo` INT NOT NULL,
  `nombreGrp` VARCHAR(45) NULL,
  `aula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codGrupo`),
  UNIQUE INDEX `codGrupo_UNIQUE` (`codGrupo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`EXISTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EXISTE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EXISTE` (
  `GRUPO_codGrupo` INT NOT NULL,
  `TITULACIÓN_idTit` INT NOT NULL,
  PRIMARY KEY (`GRUPO_codGrupo`),
  INDEX `fk_EXISTE_TITULACIÓN1_idx` (`TITULACIÓN_idTit` ASC) VISIBLE,
  CONSTRAINT `fk_EXISTE_GRUPO1`
    FOREIGN KEY (`GRUPO_codGrupo`)
    REFERENCES `mydb`.`GRUPO` (`codGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EXISTE_TITULACIÓN1`
    FOREIGN KEY (`TITULACIÓN_idTit`)
    REFERENCES `mydb`.`TITULACIÓN` (`idTit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`TELÉFONO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TELÉFONO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TELÉFONO` (
  `tlfMovil` CHAR(13) NOT NULL,
  `tlfCasa` CHAR(9) NULL,
  `USUARIO_dni` CHAR(9) NOT NULL,
  PRIMARY KEY (`tlfMovil`),
  CONSTRAINT `fk_TELÉFONO_USUARIO1`
    FOREIGN KEY (`USUARIO_dni`)
    REFERENCES `mydb`.`USUARIO` (`dni`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`DIRECCIÓN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DIRECCIÓN` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DIRECCIÓN` (
  `numCalle` INT NOT NULL,
  `nombreCalle` VARCHAR(45) NULL,
  `n.puerta` INT NULL,
  `letra` CHAR(1) NULL,
  `USUARIO_dni` CHAR(9) NOT NULL,
  PRIMARY KEY (`numCalle`),
  CONSTRAINT `fk_DIRECCIÓN_USUARIO`
    FOREIGN KEY (`USUARIO_dni`)
    REFERENCES `mydb`.`USUARIO` (`dni`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`TUTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TUTOR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TUTOR` (
  `DOCENTE_NRP` CHAR(17) NOT NULL,
  `GRUPO_codGrupo` INT NOT NULL,
  PRIMARY KEY (`DOCENTE_NRP`),
  INDEX `fk_TUTOR_GRUPO1_idx` (`GRUPO_codGrupo` ASC) VISIBLE,
  CONSTRAINT `fk_TUTOR_DOCENTE1`
    FOREIGN KEY (`DOCENTE_NRP`)
    REFERENCES `mydb`.`DOCENTE` (`NRP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TUTOR_GRUPO1`
    FOREIGN KEY (`GRUPO_codGrupo`)
    REFERENCES `mydb`.`GRUPO` (`codGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`TRABAJADOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TRABAJADOR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TRABAJADOR` (
  `dni` CHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`jefe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`jefe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`jefe` (
  `idjefe` INT NOT NULL,
  `TRABAJADOR_dni` CHAR(9) NOT NULL,
  PRIMARY KEY (`TRABAJADOR_dni`),
  INDEX `fk_jefe_TRABAJADOR1_idx` (`TRABAJADOR_dni` ASC) VISIBLE,
  CONSTRAINT `fk_jefe_TRABAJADOR1`
    FOREIGN KEY (`TRABAJADOR_dni`)
    REFERENCES `mydb`.`TRABAJADOR` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`REPRESENTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`REPRESENTA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`REPRESENTA` (
  `codRepresentante` INT NOT NULL,
  `ESTUDIANTE_numExpediente` INT NOT NULL,
  PRIMARY KEY (`codRepresentante`),
  UNIQUE INDEX `ESTUDIANTE_numExpediente_UNIQUE` (`ESTUDIANTE_numExpediente` ASC) VISIBLE,
  CONSTRAINT `fk_REPRESENTA_ESTUDIANTE1`
    FOREIGN KEY (`ESTUDIANTE_numExpediente`)
    REFERENCES `mydb`.`ESTUDIANTE` (`numExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
